version: '2'
services:
    userservice:
        build:
            context: ./userservice/
            dockerfile: dockerfile
        volumes:
            - userservice/app
    simulationservice:
        build:
            context: ./simulationservice/
            dockerfile: dockerfile
        volumes:
            - simulationservice/app
    rustsimulationservice:
        build:
            context: ./rustsimulationservice/
            dockerfile: Dockerfile
        volumes:
            - rustsimulationservice/app
    apiservice:
        build:
            context: ./apiservice/
            dockerfile: dockerfile
        volumes:
            - apiservice/app
